<?php

namespace Project\BackBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ConfirmacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfirmacionRepository extends EntityRepository
{
    public function findAllOrderedByName()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM ProjectBackBundle:Confirmacion p ORDER BY p.id DESC'
            )
            ->getResult();
    }

    public function getAllLength()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT COUNT(u.id) FROM ProjectBackBundle:Confirmacion u'
            )
            ->getSingleScalarResult();
    }
}
