<?php

namespace Project\BackBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProvinciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProvinciaRepository extends EntityRepository
{
    public function findAllOrderedByNombre()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM ProjectBackBundle:Provincia p ORDER BY p.nombre ASC'
            )
            ->getResult();
    }

    public function getAllLength()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT COUNT(u.id) FROM ProjectBackBundle:Provincia u'
            )
            ->getSingleScalarResult();
    }
}
