project_user_promover:
    path:     /usuarios/promover
    defaults: { _controller: ProjectUserBundle:Default:promover }
project_user_degradar:
    path:     /usuarios/degradar
    defaults: { _controller: ProjectUserBundle:Default:degradar }
