<?php

namespace Proyecto\PrincipalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EspacioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EspacioRepository extends EntityRepository
{
    public function findAllOrderedByNombre()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM ProyectoPrincipalBundle:Espacio p ORDER BY p.nombre ASC'
            )
            ->getResult();
    }

    public function getAllLength()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT COUNT(u.id) FROM ProyectoPrincipalBundle:Espacio u'
            )
            ->getSingleScalarResult();
    }
}
