<?php

namespace Proyecto\PrincipalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SedeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SedeRepository extends EntityRepository
{
    public function findAllOrderedById()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM ProyectoPrincipalBundle:Sede p ORDER BY p.id ASC'
            )
            ->getResult();
    }

    public function getAllLength()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT COUNT(u.id) FROM ProyectoPrincipalBundle:Sede u'
            )
            ->getSingleScalarResult();
    }
}
