parameters:
#    proyecto_principal.example.class: Proyecto\PrincipalBundle\Example

services:
#    proyecto_principal.example:
#        class: %proyecto_principal.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    proyecto_principal.form.type.servicio:
        class: Proyecto\PrincipalBundle\Form\Type\ServicioType
        tags:
            - { name: form.type, alias: servicio }

    proyecto_principal.form.type.espacio:
        class: Proyecto\PrincipalBundle\Form\Type\EspacioType
        tags:
            - { name: form.type, alias: espacio }

    proyecto_principal.form.type.sede:
        class: Proyecto\PrincipalBundle\Form\Type\SedeType
        tags:
            - { name: form.type, alias: sede }

    proyecto_principal.form.type.evento:
        class: Proyecto\PrincipalBundle\Form\Type\EventoType
        tags:
            - { name: form.type, alias: evento }